# Generated by Django 5.1.3 on 2024-12-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to='accounts.usertype')),
            ],
        ),
    ]
