# Generated by Django 5.1.3 on 2024-12-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registeredsession_accepted'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedemail',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_session', to='events.session'),
        ),
    ]
