# Generated by Django 5.1.3 on 2024-12-26 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0013_session_attendees_delete_registeredsession'),
        ('users', '0002_invitedemail_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_users', to='events.session')),
                ('user', models.ForeignKey(limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
    ]
