# Generated by Django 5.1.3 on 2024-12-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registeredsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredsession',
            name='accepted',
        ),
    ]
