# Generated by Django 5.1.3 on 2024-12-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=150, null=True)),
                ('place', models.CharField(default='Kathmandu', max_length=55)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=500)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendees', models.ManyToManyField(limit_choices_to={'status': 'Accepted', 'user_type__name': 'Guest'}, related_name='session_attendees', to='accounts.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='events.event')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_hall', to='events.hall')),
                ('speakers', models.ManyToManyField(limit_choices_to={'status': 'Accepted', 'user_type__name': 'Speaker'}, related_name='session_speakers', to='accounts.profile')),
            ],
        ),
    ]
