# Generated by Django 5.1.3 on 2024-12-23 14:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_alter_profile_phone_alter_profile_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hall_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=500)),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=events.models.session_banner_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions={"jpeg", "jpg", "png"}
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "total_seats",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "status": "Accepted",
                            "user_type__name": "Guest",
                        },
                        related_name="session_attendees",
                        to="accounts.profile",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hall",
                        to="events.hall",
                    ),
                ),
                (
                    "moderator",
                    models.ManyToManyField(
                        blank=True,
                        related_name="session_moderator",
                        to="accounts.profile",
                    ),
                ),
                (
                    "speakers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "status": "Accepted",
                            "user_type__name": "Speaker",
                        },
                        related_name="session_speakers",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_users",
                        to="accounts.profile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_users",
                        to="events.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "session")},
            },
        ),
    ]
