# Generated by Django 5.1.3 on 2024-12-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=150, null=True)),
                ('place', models.CharField(default='Kathmandu', max_length=55)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hall', models.CharField(choices=[('Hall A', 'Hall A'), ('Hall B', 'Hall B'), ('Hall C', 'Hall C')], max_length=55)),
            ],
            options={
                'ordering': ('hall', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='EventAttendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(limit_choices_to={'status': 'Accepted', 'user_type__name': 'Guest'}, on_delete=django.db.models.deletion.PROTECT, related_name='attendee', to='accounts.profile')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendee_event', to='events.event')),
            ],
            options={
                'verbose_name': 'Attendee',
                'verbose_name_plural': 'Event Attendees',
            },
        ),
        migrations.CreateModel(
            name='EventSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speakers', to='events.event')),
                ('speaker', models.ForeignKey(limit_choices_to={'status': 'Accepted', 'user_type__name': 'Speaker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_speakers', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
    ]
