# Generated by Django 5.1.3 on 2024-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, related_name='session_attendees', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'speaker'}, related_name='session_speakers', to='accounts.profile'),
        ),
    ]
