# Generated by Django 5.1.3 on 2024-12-24 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_hall_location_hall_venue_alter_session_attendees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, related_name='session_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='session_moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'speaker'}, related_name='session_speakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
