# Generated by Django 5.1.3 on 2024-12-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0003_alter_session_attendees_alter_session_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, related_name='session_attendees', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='events.hall'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'speaker'}, related_name='session_speakers', to='accounts.profile'),
        ),
    ]
