# Generated by Django 5.1.3 on 2024-12-12 04:04

import django.core.validators
import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_alter_session_attendees_alter_session_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.session_banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions={'jpeg', 'jpg', 'png'})]),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_moderator', to='accounts.profile'),
        ),
    ]
