# Generated by Django 5.1.3 on 2024-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0004_session_banner_session_description_session_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='moderator',
        ),
        migrations.AddField(
            model_name='session',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='session_moderator', to='accounts.profile'),
        ),
    ]
