# Generated by Django 5.1.3 on 2024-12-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
