# Generated by Django 5.1.3 on 2024-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0006_alter_session_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='performers',
            field=models.ManyToManyField(limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'performer'}, related_name='session_performers', to='accounts.profile'),
        ),
    ]
