# Generated by Django 5.1.3 on 2024-12-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_session_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_hall', to='events.event'),
        ),
    ]
