# Generated by Django 5.1.3 on 2024-12-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0007_session_performers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='registeredsession',
            name='user',
            field=models.ForeignKey(limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='performers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'performer'}, related_name='session_performers', to='accounts.profile'),
        ),
    ]
