# Generated by Django 5.1.3 on 2024-12-12 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_hall_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='events.event'),
        ),
    ]
