# Generated by Django 5.1.3 on 2024-12-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0009_alter_session_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsession',
            name='user',
            field=models.ForeignKey(limit_choices_to={'status': 'Accepted', 'user_type__name': 'attendee'}, on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='moderator',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted'}, related_name='session_moderator', to='accounts.profile'),
        ),
    ]
