# Generated by Django 5.1.3 on 2024-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
