# Generated by Django 5.1.3 on 2024-12-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_in_hall', to='events.hall'),
        ),
    ]
