# Generated by Django 5.1.3 on 2024-12-16 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_platform_alter_socialmedialinks_platform'),
        ('events', '0011_alter_session_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_users', to='events.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_users', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
    ]
