# Generated by Django 5.1.3 on 2024-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_registeredsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsession',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
