# Generated by Django 5.1.3 on 2024-12-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
        ('events', '0012_registeredsession_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'Accepted', 'user__user_type__name': 'attendee'}, related_name='session_attendees', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='RegisteredSession',
        ),
    ]
