# Generated by Django 5.1.3 on 2024-12-18 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_registeredsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registeredsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
