# Generated by Django 5.1.3 on 2024-12-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredsession',
            name='registered_date',
        ),
    ]
