interface TableData {
  id: number;
  registrationDate: string;
  name: string;
  socials: string;
  channel: string;
  phoneNumber: string;
  gender: string;
  age: number;
  address: string;
  email: string;
  pointOfInterest: string;
  approval_status: string;
}

export const tableData: TableData[] = [
  {
    id: 1,
    registrationDate: "2024-01-01",
    name: "John Doe",
    socials: "@johndoe",
    channel: "invited",
    phoneNumber: "123-456-7890",
    gender: "Male",
    age: 28,
    address: "123 Main St, Cityville",
    email: "johndoe@example.com",
    pointOfInterest: "Technology",
    actions: "Edit/Delete",
  },
  {
    id: 2,
    registrationDate: "2024-01-02",
    name: "Jane Smith",
    socials: "@janesmith",
    channel: "Instagram",
    phoneNumber: "987-654-3210",
    gender: "Female",
    age: 32,
    address: "456 Elm St, Townsville",
    email: "janesmith@example.com",
    pointOfInterest: "Fashion",
    actions: "Edit/Delete",
  },
  {
    id: 3,
    registrationDate: "2024-01-03",
    name: "Alice Johnson",
    socials: "@alicejohnson",
    channel: "TikTok",
    phoneNumber: "456-789-0123",
    gender: "Female",
    age: 25,
    address: "789 Maple Ave, Villagetown",
    email: "alicej@example.com",
    pointOfInterest: "Dance",
    actions: "Edit/Delete",
  },
  {
    id: 4,
    registrationDate: "2024-01-04",
    name: "Bob Brown",
    socials: "@bobbrown",
    channel: "Facebook",
    phoneNumber: "321-654-9870",
    gender: "Male",
    age: 35,
    address: "321 Pine Rd, Metrocity",
    email: "bobb@example.com",
    pointOfInterest: "Cooking",
    actions: "Edit/Delete",
  },
  {
    id: 5,
    registrationDate: "2024-01-05",
    name: "Charlie Green",
    socials: "@charliegreen",
    channel: "Twitter",
    phoneNumber: "654-321-0987",
    gender: "Non-Binary",
    age: 29,
    address: "654 Oak St, Bigtown",
    email: "charlieg@example.com",
    pointOfInterest: "Photography",
    actions: "Edit/Delete",
  },
  {
    id: 6,
    registrationDate: "2024-01-06",
    name: "Daniel White",
    socials: "@danielwhite",
    channel: "LinkedIn",
    phoneNumber: "789-012-3456",
    gender: "Male",
    age: 40,
    address: "987 Cedar Ln, Smallville",
    email: "danielw@example.com",
    pointOfInterest: "Business",
    actions: "Edit/Delete",
  },
  {
    id: 7,
    registrationDate: "2024-01-07",
    name: "Ella Blue",
    socials: "@ellablue",
    channel: "Snapchat",
    phoneNumber: "012-345-6789",
    gender: "Female",
    age: 22,
    address: "321 Birch Dr, Middletown",
    email: "ellab@example.com",
    pointOfInterest: "Travel",
    actions: "Edit/Delete",
  },
  {
    id: 8,
    registrationDate: "2024-01-08",
    name: "Frank Black",
    socials: "@frankblack",
    channel: "Reddit",
    phoneNumber: "345-678-9012",
    gender: "Male",
    age: 50,
    address: "654 Walnut St, Uptown",
    email: "frankb@example.com",
    pointOfInterest: "Gaming",
    actions: "Edit/Delete",
  },
  {
    id: 9,
    registrationDate: "2024-01-09",
    name: "Grace Silver",
    socials: "@gracesilver",
    channel: "Pinterest",
    phoneNumber: "789-012-3456",
    gender: "Female",
    age: 27,
    address: "987 Aspen Ct, Hometown",
    email: "graces@example.com",
    pointOfInterest: "Art",
    actions: "Edit/Delete",
  },
  {
    id: 10,
    registrationDate: "2024-01-10",
    name: "Hank Gold",
    socials: "@hankgold",
    channel: "YouTube",
    phoneNumber: "012-345-6789",
    gender: "Male",
    age: 45,
    address: "123 Sycamore Ln, Capital City",
    email: "hankg@example.com",
    pointOfInterest: "DIY Projects",
    actions: "Edit/Delete",
  },
  {
    id: 11,
    registrationDate: "2024-01-11",
    name: "Isla Orange",
    socials: "@islaorange",
    channel: "TikTok",
    phoneNumber: "234-567-8901",
    gender: "Female",
    age: 19,
    address: "234 Magnolia Ave, Downtown",
    email: "islao@example.com",
    pointOfInterest: "Music",
    actions: "Edit/Delete",
  },
  {
    id: 12,
    registrationDate: "2024-01-12",
    name: "Jack Purple",
    socials: "@jackpurple",
    channel: "Instagram",
    phoneNumber: "678-901-2345",
    gender: "Male",
    age: 30,
    address: "567 Palm Blvd, Suburbia",
    email: "jackp@example.com",
    pointOfInterest: "Fitness",
    actions: "Edit/Delete",
  },
  {
    id: 13,
    registrationDate: "2024-01-13",
    name: "Karen Teal",
    socials: "@karenteal",
    channel: "Facebook",
    phoneNumber: "901-234-5678",
    gender: "Female",
    age: 38,
    address: "890 Spruce Dr, Coastal City",
    email: "karent@example.com",
    pointOfInterest: "Cooking",
    actions: "Edit/Delete",
  },
  {
    id: 14,
    registrationDate: "2024-01-14",
    name: "Leo Yellow",
    socials: "@leoyellow",
    channel: "Twitter",
    phoneNumber: "345-678-9012",
    gender: "Male",
    age: 33,
    address: "234 Poplar St, River Town",
    email: "leoy@example.com",
    pointOfInterest: "Comedy",
    actions: "Edit/Delete",
  },
  {
    id: 15,
    registrationDate: "2024-01-15",
    name: "Mia Violet",
    socials: "@miaviolet",
    channel: "Snapchat",
    phoneNumber: "567-890-1234",
    gender: "Female",
    age: 21,
    address: "456 Willow Way, Sunnyvale",
    email: "miav@example.com",
    pointOfInterest: "Fashion",
    actions: "Edit/Delete",
  },
];
