# Generated by Django 5.1.3 on 2024-12-31 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialinks',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_media', to='accounts.profile'),
        ),
    ]
