# Generated by Django 5.1.3 on 2024-12-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': '2. Districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': '1. Provinces',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_in_district', to='federal.district')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': '3. Municipalities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_in_province', to='federal.province'),
        ),
    ]
